### ISSUE TITLE
devjars in ./libs still dont compile

### ISSUE THREAD

**Issue by MattDahEpic** [MinecraftForge/ForgeGradle#300]
FG 2.0.1 snapshot
Forge 1.8.8-11.14.4.1576

**Comment by AbrarSyed** [comment]
there are no 2.0.1 snapshots.. its either 2.0.1 stable, 2.0.2 stable, or 2.0-snapshot.... and it should be fixed in either 2.0.2 or 2.0-snapshot

**Comment by GirafiStudios** [comment]
Well you forgot the most important one in @MattDahEpics case, 2.1-snapshot. Which is required for Forge 1.8.8
